---
# System
- name: Update /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: 0644
    backup: yes
  become: true
  become_method: sudo

# ~/dev directory
- name: Create dev directory
  file:
    path: ~/dev
    state: directory
    mode: 0755

# Tools
- name: Tool repository setup
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ tool_repos }}"

# **env
- name: Install *envs
  shell: "{{ansible_user_shell}} -i -c 'anyenv install {{ item }}'"
  args:
    creates: "~/.anyenv/envs/{{ item }}"
  with_items:
    - "{{ envs }}"

# Ruby
- name: Install ruby
  shell: "{{ansible_user_shell}} -i -c 'rbenv install 2.1.2'"
  args:
    creates: ~/.anyenv/envs/rbenv/versions/2.1.2

- name: Set ruby version
  shell: "{{ansible_user_shell}} -i -c 'rbenv global 2.1.2'"

- name: Install gems globally
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ global_gems }}"

# MongoDB
- name: Create mongod.conf
  template:
    src: templates/mongod_conf.j2
    dest: /usr/local/etc/mongod.conf
    mode: 0644
    backup: yes

- name: Restart MongoDB
  shell: "brew services restart homebrew/versions/mongodb30"

# *** Commented out because fails
#- name: Get Bitbucket repositories
#  git:
#    repo: "git@bitbucket.org:efsol/{{ item }}.git"
#    dest: "~/dev/{{ item }}"
#    depth: 100
#    accept_hostkey: yes
#  with_items:
#    - "{{ bitbucket_repos }}"
